#!/usr/bin/python
from waflib.Build import BuildContext
from waflib.Configure import ConfigurationContext
from waflib.Node import Node
from typing import List

import idpdbuild.Build
import idpdbuild.Configure
from idpdbuild.csvw.Csv2RdfTask import Csv2RdfTask
from idpdbuild.csvw.CsvLintTask import CsvLintTask


def configure(ctx: ConfigurationContext):
    idpdbuild.Configure.configure(ctx)


def build(bld: BuildContext):
    code_lists: List[Node] = bld.path.ant_glob("codelists/*.csv-metadata.json")
    CsvLintTask.register_tasks(bld, code_lists)
    Csv2RdfTask.register_tasks(bld, code_lists)
