#!/usr/bin/python
import waflib.Node
from waflib.Build import BuildContext
from waflib.Configure import ConfigurationContext
from waflib.Context import Context
from waflib.Node import Node
from typing import List

import idpdbuild.Build
import idpdbuild.Configure
from idpdbuild.DuplicateFileTask import DuplicateFileTask


def configure(ctx: ConfigurationContext):
    idpdbuild.Configure.configure(ctx)


def step_one(ctx: Context):
    print(f"Running step one in {ctx.path}")


def build(bld: BuildContext):
    idpdbuild.Build.build(bld)
    code_lists: List[Node] = bld.path.ant_glob("codelists/*.csv")
    print(code_lists)
    for code_list in code_lists:
        bld.add_to_group(DuplicateFileTask(bld, code_list))

    # bld(SecondTask(env=bld.env.derive()))
